# Generated by Django 6.0 on 2026-01-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_chart_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD10Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icd_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("short_description", models.CharField(max_length=500)),
                ("long_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CodeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_assignments",
                        to="app.note",
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_assignments",
                        to="app.icd10code",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_score"],
                "unique_together": {("note", "icd_code")},
            },
        ),
    ]
